name: Test Java App
on:
  push:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 20
        uses: actions/checkout@v4
        with:
            java-version: '20'
            distribution: 'temurin'
            cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml


      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
