name: Test Java App
on:
  push:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
            java-version: '20'
            distribution: 'temurin'
            cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
